#ifndef ARQUIVO_H
#define ARQUIVO_H

#define NUM_ESTADOS 26
#define NUM_SIMBOLOS 77 //52 letras, 10 digitos, 15 simbolos (:	 =	 +	-	<	>	;	,	(	)	{	}	'	\t	\n .)

int transicao[NUM_ESTADOS][NUM_SIMBOLOS] = {
    4	1	6	10	8	9	11	15	18	19	21	20	22	24	0	0	0
2	1	3	3	3	3	3	3	3	3	3	3	3	3	3	3	3
ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO	ERRO_NUMERO_MAL_FORMADO
TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT	TK_NUM_INT
4	4	5	5	5	5	5	5	5	5	5	5	5	5	5	5	5
TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID	TK_ID
26	26	26	7	26	26	26	26	26	26	26	26	26	26	26	26	26
TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO	TK_ATRIBUIÇÃO
SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA	SIMB_SOMA
SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB	SIMB_SUB
SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL	SIMB_IGUAL_IGUAL
12	12	12	14	12	12	12	13	12	12	12	12	12	12	12	12	12
SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR	SIMB_MENOR
SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR	SIMB_MENOR_MAIOR
SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL	SIMB_MENOR_IGUAL
16	16	16	17	16	16	16	16	16	16	16	16	16	16	16	16	16
SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR	SIMB_MAIOR
SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL	SIMB_MAIOR_IGUAL
SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG	SIMB_PONT_VIRG
SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA	SIMB_VIRGULA
SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P	SIMB_FECHA_P
SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P	SIMB_ABRE_P
22	22	22	22	22	22	22	22	22	22	22	22	22	23	22	22	22
COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO	COMENTÁRIO
ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO	ERRO_IDENT_MAL_FORMADO
ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO	ERRO_ATRIB_MAL_FORMADO
}

#endif