#include<stdio.h>
#include "automato.h"

int matriz_transicao[NUM_ESTADOS][NUM_SIMBOLOS] = { // PRECISA INCLUIR COLUNA DE .
    // Estado 0
    {4, 1, 6, 10, 8, 9, 11, 15, 18, 19, 21, 20, 22, 24, 0, 0, 0},
    
    // Estado 1
    {2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3},
    
    // Estado 2
    {ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO,
     ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO,
     ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO,
     ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO,
     ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO,
     ERRO_NUMERO_MAL_FORMADO, ERRO_NUMERO_MAL_FORMADO},
    
    // Estado 3
    {TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT,
     TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT,
     TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT, TK_NUM_INT},
    
    // Estado 4
    {4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
    
    // Estado 5
    {TK_ID, TK_ID, TK_ID, TK_ID, TK_ID, TK_ID, TK_ID, TK_ID, TK_ID, TK_ID,
     TK_ID, TK_ID, TK_ID, TK_ID, TK_ID, TK_ID, TK_ID},
    
    // Estado 6
    {26, 26, 26, 7, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26},
    
    // Estado 7
    {TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO,
     TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO,
     TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO, TK_ATRIBUICAO,
     TK_ATRIBUICAO, TK_ATRIBUICAO},
    
    // Estado 8
    {SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA,
     SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA,
     SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA, SIMB_SOMA},
    
    // Estado 9
    {SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB,
     SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB,
     SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB, SIMB_SUB},

    // Estado 10
    {SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL,
     SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL,
     SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL,
     SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL, SIMB_IGUAL_IGUAL,
     SIMB_IGUAL_IGUAL},

    // Estado 11
    {12, 12, 12, 14, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12},

    // Estado 12
    {SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR,
     SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR,
     SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR, SIMB_MENOR},

    // Estado 13
    {SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR,
     SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR,
     SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR,
     SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR, SIMB_MENOR_MAIOR,
     SIMB_MENOR_MAIOR},

    // Estado 14
    {SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL,
     SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL,
     SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL,
     SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL, SIMB_MENOR_IGUAL,
     SIMB_MENOR_IGUAL},

    // Estado 15
    {16, 16, 16, 17, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16},

    // Estado 16
    {SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR,
     SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR,
     SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR, SIMB_MAIOR},

    // Estado 17
    {SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL,
     SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL,
     SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL,
     SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL, SIMB_MAIOR_IGUAL,
     SIMB_MAIOR_IGUAL},

    // Estado 18
    {SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG,
     SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG,
     SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG, SIMB_PONT_VIRG,
     SIMB_PONT_VIRG, SIMB_PONT_VIRG},

    // Estado 19
    {SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA,
     SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA,
     SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA, SIMB_VIRGULA,
     SIMB_VIRGULA, SIMB_VIRGULA},

    // Estado 20
    {SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P,
     SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P,
     SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P, SIMB_FECHA_P,
     SIMB_FECHA_P, SIMB_FECHA_P},

    // Estado 21
    {SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P,
     SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P,
     SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P, SIMB_ABRE_P,
     SIMB_ABRE_P, SIMB_ABRE_P},

    // Estado 22
    {22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 22, 22, 22},

    // Estado 23
    {COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO,
     COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO,
     COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO, COMENTARIO},

    // Estado 24
    {ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO,
     ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO,
     ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO,
     ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO,
     ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO,
     ERRO_IDENT_MAL_FORMADO, ERRO_IDENT_MAL_FORMADO},

    // Estado 25
    {ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO,
     ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO,
     ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO,
     ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO,
     ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO,
     ERRO_ATRIB_MAL_FORMADO, ERRO_ATRIB_MAL_FORMADO}
};

int transicao(char char_prox, int estado_atual){
    int coluna_char;
    
    return matriz_transicao[estado_atual][coluna_char];
}